name: Playwright Test

on: 
  push:
    branches: [master]

jobs: 
  playwrightTest:
    runs-on: ubuntu-latest 
    container: 
      image: mcr.microsoft.com/playwright:v1.29.1-focal
      env:
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Start the shopping store application
        run: |
          echo "start the shopping store application"
          chmod +x ./shopping-store-linux-amd64
          ./shopping-store-linux-amd64 &

      - name: Install dependencies
        run: |
          echo "install dependencies from lockfile"
          npm ci 

      - name: Run Playwright tests
        run: |
          echo "run playwright tests"
          npm run test:ci
